#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl3,  bump3,          sensorTouch)
#pragma config(Sensor, dgtl4,  ultrasonic,     sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, redLED,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(ultrasonic) < 27)
	{
		startMotor(motor1, 15);
	}
	stopMotor(motor1);
	while (1==1)
	{
		if (SensorValue(bump1) == 1)
		{
			turnLEDOff(yellowLED);
			turnLEDOff(redLED);
			while(SensorValue(ultrasonic) < 27)
			{
				startMotor(motor1, 15);
			}
			stopMotor(motor1);
			turnLEDOn(greenLED);
		}
		if (SensorValue(bump2) == 1)
		{
			clearTimer(T1);
			turnLEDOff(greenLED);
			turnLEDOff(redLED);
			while (SensorValue(ultrasonic) > 19)
			{
				startMotor(motor1, -20);
			}
			while (SensorValue(ultrasonic) < 19)
			{
				startMotor(motor1, 15);
			}
			stopMotor(motor1);
			turnLEDOn(yellowLED);
		}
		if (SensorValue(bump3) == 1)
		{
			clearTimer(T1);
			turnLEDOff(greenLED);
			turnLEDOff(yellowLED);
			while (SensorValue(ultrasonic) > 8)
			{
				startMotor(motor1, -20);
			}
			turnLEDOn(redLED);
			stopMotor(motor1);
		}
		if (time1[T1] >= 6000)
		{
			clearTimer(T1);
			turnLEDOff(greenLED);
			turnLEDOff(yellowLED);
			turnLEDOff(redLED);
			while (SensorValue(ultrasonic) < 27)
			{
				startMotor(motor1, 15);
			}
			stopMotor(motor1);
			turnLEDOn(greenLED);
		}
	}
}
